export enum OrdersCreateFields {
  countryId = "countryId",
  cryptoCurrencySellId = "cryptoCurrencySellId",
  cryptoCurrencySellPrice = "cryptoCurrencySellPrice",
  cryptoCurrencyBuyId = "cryptoCurrencyBuyId",
  cryptoCurrencyBuyPrice = "cryptoCurrencyBuyPrice",
  paymentMethodId = "paymentMethodId",
  bankName = "bankName",
  marginProfit = "marginProfit",
  isAutoAdjustTransactionLimit = "isAutoAdjustTransactionLimit",
  termsOfTrade = "termsOfTrade",
  isVerifiedUsersOnly = "isVerifiedUsersOnly",
  isTrustedUsersOnly = "isTrustedUsersOnly",
  isIdentifyUsersBeforeContinueTrade = "isIdentifyUsersBeforeContinueTrade",
}
